# Incorporate isolate sequences into master tree of DADA2 seqs
* Align isolate seqs using SSU_align
* Mask sequences based on same mask as used for sequences from Exp10 
* Append sequences to create new fasta with both sets of sequences
* Create master tree using FastTree
* Use qiime environment and set kernel to Python 2

In [26]:
workDir = '/home/be68/Hyphosphere/Exp10/MasterTree/'
maskDir = '/home/be68/Hyphosphere/Exp10/DADA2/'
IsolateSeqDir = '/home/be68/Hyphosphere/Exp10/MasterTree/'
IsolateSeqFile = 'IsolateSeqs.fasta'


nprocs = 3

In [50]:
import os
import numpy as np
#import entrez.direct
from cogent.app.fasttree import build_tree_from_alignment
from cogent import DNA, LoadSeqs
from Bio import Entrez, SeqIO
from pandas import *
Entrez.email = "be68@cornell.edu"
#from IPython.display import display, Image, SVG
#from cogent3 import LoadSeqs, FastTree

In [16]:
if not os.path.isdir(workDir):
    os.mkdir(workDir)

In [17]:
%cd $workDir

/data/home/be68/Hyphosphere/Exp10/MasterTree

In [18]:
!cd $workDir; ln -f -s $IsolateSeqDir$IsolateSeqFile

ln: ‘/home/be68/Hyphosphere/Exp10/MasterTree/IsolateSeqs.fasta’ and ‘./IsolateSeqs.fasta’ are the same file

In [19]:
!cd $workDir; head $IsolateSeqFile

In [20]:
!printf "Number of OTUs in fasta: "
!cd $workDir; grep -c ">" $IsolateSeqFile

Number of OTUs in fasta: 170

## Using SSU-Align to align seqs and masking based on alignment posterior probabilities of Exp10 - ASV set.

In [24]:
!cd $workDir; ssu-prep -f -x -b 50 --rfonly --dna $IsolateSeqFile ssu_aln 3

# _ssu-prep :: prepare SSU rRNA sequences for parallel ssu-align jobs
# SSU-ALIGN 0.1.1 (Feb 2016)
# Copyright (C) 2016 Howard Hughes Medical Institute
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# command: _ssu-prep -x -f -b 50 --dna --rfonly IsolateSeqs.fasta ssu_aln 3
# date:    Fri Apr 19 15:40:32 2019
#
# Validating input sequence file ... done.
#
# Preparing 3 ssu-align jobs ...
# Partitioning seqs with goal of equalizing total number of nucleotides per job ...
#
# output file name      description
# --------------------  ---------------------------------------------------
  ssu_aln/IsolateSeqs.fasta.1  partition 1 FASTA sequence file (55 seqs; 70726 nt)
  ssu_aln/IsolateSeqs.fasta.2  partition 2 FASTA sequence file (56 seqs; 70104 nt)
  ssu_aln/IsolateSeqs.fasta.3  partition 3 FASTA sequence file (54 seqs; 67718 nt)
  ssu_aln.ssu-align.sh  shell script that will execute 3 ssu-align jobs
#
################################################################################
# To execute all 3 ssu-align jobs, run the shell script with the command:
#	"ssu_aln.ssu-align.sh"
# (it is an executable file)
################################################################################
#
# The final job will merge the output from all jobs once they are all finished.
#
# If one or more jobs fail: rerun the failed jobs, wait for them to finish,
# and then perform manual merge from this directory by executing:
#	ssu-merge ssu_aln
#
# List of executed commands saved in:     ssu_aln/ssu_aln.ssu-prep.log.
# Output printed to the screen saved in:  ssu_aln/ssu_aln.ssu-prep.sum.
#
# CPU time:  00:00:00.16  (hh:mm:ss)
#

In [25]:
!cd $workDir; ./ssu_aln.ssu-align.sh

# Executing: ssu-align -b 50 --dna --rfonly ssu_aln/IsolateSeqs.fasta.1 ssu_aln/ssu_aln.1 > /dev/null &
# Executing: ssu-align -b 50 --dna --rfonly ssu_aln/IsolateSeqs.fasta.2 ssu_aln/ssu_aln.2 > /dev/null &
# Executing: ssu-align --merge 3 -b 50 --dna --rfonly ssu_aln/IsolateSeqs.fasta.3 ssu_aln/ssu_aln.3
# _ssu-align :: align SSU rRNA sequences
# SSU-ALIGN 0.1.1 (Feb 2016)
# Copyright (C) 2016 Howard Hughes Medical Institute
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# command: _ssu-align --merge 3 -b 50 --dna --rfonly ssu_aln/IsolateSeqs.fasta.3 ssu_aln/ssu_aln.3
# date:    Fri Apr 19 15:40:58 2019
#
# Validating input sequence file ... done.
#
# Stage 1: Determining SSU start/end positions and best-matching models...
#
# output file name            description
# --------------------------  -------------------------------------------
  ssu_aln.3.tab               locations/scores of hits defined by HMM(s)
  ssu_aln.3.bacteria.hitlist  list of sequences to align with bacteria CM
  ssu_aln.3.bacteria.fa            54 sequences to align with bacteria CM
#
# Stage 2: Aligning each sequence to its best-matching model...
#
# output file name            description
# --------------------------  ---------------------------------------
  ssu_aln.3.bacteria.stk      bacteria alignment
  ssu_aln.3.bacteria.cmalign  bacteria cmalign output
  ssu_aln.3.bacteria.ifile    bacteria insert info
  ssu_aln.3.scores            list of CM/HMM scores for each sequence
#
# Summary statistics:
#
# model or       number  fraction        average   average
# category      of seqs  of total         length  coverage    nucleotides
# ------------  -------  --------  -------------  --------  -------------
  *input*            54    1.0000        1254.04    1.0000          67718
#
  archaea             0    0.0000              -         -              0
  bacteria           54    1.0000        1252.67    0.9989          67644
  eukarya             0    0.0000              -         -              0
#
  *all-models*       54    1.0000        1252.67    0.9989          67644
  *no-models*         0    0.0000              -         -              0
#
# Speed statistics:
#
# stage      num seqs  seq/sec  seq/sec/model    nucleotides    nt/sec
# ---------  --------  -------  -------------  -------------  --------
  search           54    1.963          0.654          67718    2462.2
  alignment        54    1.086          1.086          67644    1360.9
#
#
# List of executed commands saved in:     ssu_aln.3.ssu-align.log.
# Output printed to the screen saved in:  ssu_aln.3.ssu-align.sum.
#
# All output files created in directory ./ssu_aln/ssu_aln.3/
#
# CPU time (search):     00:00:27.50  (hh:mm:ss)
# CPU time (alignment):  00:00:49.71  (hh:mm:ss)
# CPU time (total):      00:01:17.68  (hh:mm:ss)
#
################################################################################
#
# Alignments successfully created.
#
# Checking/waiting for other jobs to finish before merging...
#
# Job 3 (dir: ssu_aln/ssu_aln.3) completed successfully! 2/3 still incomplete.
# Job 1 (dir: ssu_aln/ssu_aln.1) completed successfully! 1/3 still incomplete.
# Job 2 (dir: ssu_aln/ssu_aln.2) completed successfully! 0/3 still incomplete.
#
# All 3 jobs successfully completed.
# About to merge their output:
#
# Executing:  ssu-merge ssu_aln
#
################################################################################
#
# _ssu-merge :: merge SSU rRNA alignments
# SSU-ALIGN 0.1.1 (Feb 2016)
# Copyright (C) 2016 Howard Hughes Medical Institute
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# command: _ssu-merge ssu_aln
# date:    Fri Apr 19 15:42:22 2019
#
# Merging files from 3 ssu-align runs...
#
#                                     # files     # seqs
# merged file name          CM name    merged     merged
# ------------------------  --------  -------  ---------
  ssu_aln.tab               -               3          -
  ssu_aln.scores            -               3          -
  ssu_aln.ssu-align.sum     -               3          -
  ssu_aln.ssu-align.log     -               3          -
#
  ssu_aln.bacteria.fa       bacteria        3        165
  ssu_aln.bacteria.hitlist  bacteria        3        165
  ssu_aln.bacteria.cmalign  bacteria        3        165
  ssu_aln.bacteria.ifile    bacteria        3        165
  ssu_aln.bacteria.stk      bacteria        3        165
#
#
# Summary statistics:
#
# model or       number  fraction        average   average
# category      of seqs  of total         length  coverage    nucleotides
# ------------  -------  --------  -------------  --------  -------------
  *input*           165    1.0000        1263.93    1.0000         208548
#
  archaea             0    0.0000              -         -              0
  bacteria          165    1.0000        1262.46    0.9988         208306
  eukarya             0    0.0000              -         -              0
#
  *all-models*      165    1.0000        1262.46    0.9988         208306
  *no-models*         0    0.0000              -         -              0
#
# Speed statistics:
#
# stage      num seqs  seq/sec  seq/sec/model    nucleotides    nt/sec
# ---------  --------  -------  -------------  -------------  --------
  search          165  165.000         55.000         208548  208548.0
  alignment       165  165.000        165.000         208306  208306.0
#
# Summed ssu-align CPU time (search):     00:00:00.00  (hh:mm:ss)
# Summed ssu-align CPU time (alignment):  00:00:00.00  (hh:mm:ss)
# Summed ssu-align CPU time (total):      00:00:00.00  (hh:mm:ss)
#
# Cleaning up by removing original files that were just merged ... done.
#
# List of executed commands saved in:     ssu_aln.ssu-merge.log.
# Output printed to the screen saved in:  ssu_aln.ssu-merge.sum.
#
# All output files created in directory ./ssu_aln/
#
# CPU time:  00:00:00.11  (hh:mm:ss)
#

In [27]:
!cd $workDir; ssu-mask -s $maskDir/ssu_aln/ssu_aln.bacteria.mask --dna --afa ssu_aln/

# _ssu-mask :: mask SSU rRNA alignments
# SSU-ALIGN 0.1.1 (Feb 2016)
# Copyright (C) 2016 Howard Hughes Medical Institute
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# command: _ssu-mask -s /home/be68/Hyphosphere/Exp10/DADA2//ssu_aln/ssu_aln.bacteria.mask --afa --dna ssu_aln/
# date:    Fri Apr 19 15:44:03 2019
#
# Masking alignments using pre-existing masks...
#
#                                                     mask
#                                                 ------------
# file name                  in/out  type  #cols  incl.  excl.
# -------------------------  ------  ----  -----  -----  -----
  ssu_aln.bacteria.stk        input   aln   1582      -      -
  ssu_aln.bacteria.mask       input  mask   1582    248   1334
  ssu_aln.bacteria.mask.pdf  output   pdf   1582    248   1334
  ssu_aln.bacteria.mask.afa  output   aln    248      -      -
#
# All attempts to draw structure diagrams of masks were successful.
#
# List of executed commands saved in:     ssu_aln.ssu-mask.log.
# Output printed to the screen saved in:  ssu_aln.ssu-mask.sum.
#
# All output files created in directory ./ssu_aln/
#
# CPU time:  00:00:01.39  (hh:mm:ss)
#

In [ ]:
# Append masked alignments

In [28]:
!cd $workDir; cat $maskDir/ssu_aln/ssu_aln.bacteria.mask.afa ssu_aln/ssu_aln.bacteria.mask.afa > aln_for_tree.fasta

In [30]:
!tail aln_for_tree.fasta

TAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACATCTGATACTGGCAAGCTTGAG
TCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAA
TACCGGTGGCGAAGGCGGCCCCCTGGACGAACTGACGCTCAGGTGCGAAAGCGTGGGGAG
CAAACAGG
>BE277
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGT
TAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACATCTGATACTGGCAAGCTTGAG
TCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAA
TACCGGTGGCGAAGGCGGCCCCCTGGACGAACTGACGCTCAGGTGCGAAAGCGTGGGGAG
CAAACAGG

## Inferring and rooting the tree

In [32]:
aln = LoadSeqs(os.path.join(workDir, 'aln_for_tree.fasta'), moltype=DNA)
t_unroot = build_tree_from_alignment(aln, moltype=DNA)

* Using sulfalobus sso_acc = "X90478" as the outgroup leads to an error downstream when calculating unifrac distances, instead I checked the tree with sulfalobus as root and identified ASV1721 as an outgroup.  Rooted the tree to ASV1721 instead and received no errors during the analysis

In [33]:
t_rooted = t_unroot.rootedWithTip('ASV1721')

In [34]:
t_rooted.writeToFile(os.path.join(workDir, 'Master.tree'))

In [ ]:
## Subset tree with hyphal ASVs and top

In [ ]:
## get tip names of isolates

In [154]:
file_to_open = os.path.join(IsolateSeqDir, IsolateSeqFile)
IsolateList = []

for record in SeqIO.parse(file_to_open, "fasta") :
       IsolateList.append(record.id)#+"\n"+str(record.seq)+"\n")

print(IsolateList)

['BE26', 'BE27', 'BE28', 'BE29', 'BE30', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 'BE36', 'BE38', 'BE39', 'BE40', 'BE41', 'BE42', 'BE43', 'BE44', 'BE45', 'BE46', 'BE47', 'BE48', 'BE49', 'BE50', 'BE51', 'BE52', 'BE53', 'BE54', 'BE55', 'BE56', 'BE57', 'BE59', 'BE60', 'BE61', 'BE62', 'BE63', 'BE64', 'BE65', 'BE65B', 'BE66', 'BE68', 'BE69', 'BE70', 'BE71', 'BE72', 'BE74', 'BE75', 'BE76', 'BE79', 'BE80', 'BE81', 'BE82', 'BE83', 'BE84', 'BE85', 'BE88', 'BE91', 'BE92', 'BE93', 'BE94', 'BE95', 'BE96', 'BE97', 'BE98', 'BE100', 'BE101', 'BE102', 'BE103', 'BE104', 'BE105', 'BE107', 'BE108', 'BE109', 'BE110', 'BE112', 'BE113', 'BE114', 'BE115', 'BE116', 'BE117', 'BE118', 'BE120', 'BE121', 'BE122', 'BE123', 'BE124', 'BE125', 'BE126', 'BE127', 'BE128', 'BE153', 'BE154', 'BE156', 'BE157', 'BE159', 'BE163', 'BE164', 'BE166', 'BE167', 'BE168', 'BE170', 'BE171', 'BE172', 'BE173', 'BE177', 'BE178', 'BE179', 'BE180', 'BE181', 'BE182', 'BE183', 'BE184', 'BE186', 'BE187', 'BE190', 'BE191', 'BE193', 'BE194', 'BE195', 'BE196', 'BE197', 'BE198', 'BE201', 'BE203', 'BE206', 'BE207', 'BE212', 'BE213', 'BE215', 'BE216', 'BE219', 'BE220', 'BE222', 'BE223', 'BE224', 'BE228', 'BE231', 'BE232', 'BE233', 'BE234', 'BE235', 'BE236', 'BE239', 'BE240', 'BE241', 'BE242', 'BE243', 'BE248', 'BE249', 'BE251', 'BE254', 'BE255', 'BE256', 'BE257', 'BE258', 'BE259', 'BE260', 'BE261', 'BE264', 'BE265', 'BE268', 'BE270', 'BE275', 'BE276', 'BE277']

## Import blast tablesb

In [52]:
!head Isolate-ASV_blast

BE26	ASV193	100.00	253	0	0	444	696	1	253	3e-132	  468
BE27	ASV193	100.00	253	0	0	450	702	1	253	3e-132	  468
BE28	ASV193	100.00	253	0	0	452	704	1	253	3e-132	  468
BE29	ASV39	100.00	253	0	0	433	685	1	253	3e-132	  468
BE30	ASV39	100.00	253	0	0	433	685	1	253	3e-132	  468
BE31	ASV81	100.00	253	0	0	417	669	1	253	3e-132	  468
BE32	ASV81	100.00	253	0	0	417	669	1	253	3e-132	  468
BE33	ASV3899	100.00	253	0	0	419	671	1	253	2e-132	  468
BE34	ASV81	100.00	253	0	0	418	670	1	253	3e-132	  468
BE35	ASV4861	98.81	253	3	0	417	669	1	253	2e-127	  451

In [58]:
df = pandas.read_table('Isolate-ASV_blast', sep = "\t", header=None)
df.columns = ['qseqid','sseqid',
'pident',
'length',
'mismatch',
'gapopen',
'qstart',
'qend',
'sstart',
'send',
'evalue',
'bitscore']
df.head()

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
0,BE26,ASV193,100.0,253,0,0,444,696,1,253,3.000000e-132,468
1,BE27,ASV193,100.0,253,0,0,450,702,1,253,3.000000e-132,468
2,BE28,ASV193,100.0,253,0,0,452,704,1,253,3.000000e-132,468
3,BE29,ASV39,100.0,253,0,0,433,685,1,253,3.000000e-132,468
4,BE30,ASV39,100.0,253,0,0,433,685,1,253,3.000000e-132,468

In [59]:
df

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
0,BE26,ASV193,100.00,253,0,0,444,696,1,253,3.000000e-132,468
1,BE27,ASV193,100.00,253,0,0,450,702,1,253,3.000000e-132,468
2,BE28,ASV193,100.00,253,0,0,452,704,1,253,3.000000e-132,468
3,BE29,ASV39,100.00,253,0,0,433,685,1,253,3.000000e-132,468
4,BE30,ASV39,100.00,253,0,0,433,685,1,253,3.000000e-132,468
5,BE31,ASV81,100.00,253,0,0,417,669,1,253,3.000000e-132,468
6,BE32,ASV81,100.00,253,0,0,417,669,1,253,3.000000e-132,468
7,BE33,ASV3899,100.00,253,0,0,419,671,1,253,2.000000e-132,468
8,BE34,ASV81,100.00,253,0,0,418,670,1,253,3.000000e-132,468
9,BE35,ASV4861,98.81,253,3,0,417,669,1,253,2.000000e-127,451
10,BE36,ASV5271,95.63,252,11,0,438,689,1,252,2.000000e-113,405
11,BE38,ASV91,100.00,253,0,0,436,688,1,253,3.000000e-132,468
12,BE39,ASV4861,98.81,253,3,0,419,671,1,253,3.000000e-127,451
13,BE40,ASV1915,100.00,253,0,0,433,685,1,253,3.000000e-132,468
14,BE41,ASV188,100.00,253,0,0,411,663,1,253,3.000000e-132,468
15,BE42,ASV420,99.60,253,1,0,436,688,1,253,3.000000e-131,464
16,BE43,ASV193,100.00,253,0,0,450,702,1,253,3.000000e-132,468
17,BE44,ASV5115,100.00,253,0,0,436,688,1,253,3.000000e-132,468
18,BE45,ASV193,100.00,253,0,0,448,700,1,253,3.000000e-132,468
19,BE46,ASV393,100.00,253,0,0,435,687,1,253,3.000000e-132,468
20,BE47,ASV1106,100.00,253,0,0,434,686,1,253,3.000000e-132,468
21,BE48,ASV452,100.00,253,0,0,442,694,1,253,3.000000e-132,468
22,BE49,ASV765,100.00,253,0,0,383,635,1,253,2.000000e-132,468
23,BE50,ASV4621,100.00,253,0,0,455,707,1,253,3.000000e-132,468
24,BE51,ASV430,100.00,253,0,0,416,668,1,253,2.000000e-132,468
25,BE52,ASV12,100.00,253,0,0,433,685,1,253,3.000000e-132,468
26,BE53,ASV1592,100.00,253,0,0,380,632,1,253,2.000000e-132,468
27,BE54,ASV188,100.00,253,0,0,409,661,1,253,3.000000e-132,468
28,BE55,ASV393,100.00,253,0,0,434,686,1,253,3.000000e-132,468
29,BE56,ASV1350,98.42,253,4,0,433,685,1,253,1.000000e-125,446
...,...,...,...,...,...,...,...,...,...,...,...,...
134,BE228,ASV452,95.65,253,11,0,443,695,1,253,6.000000e-114,407
135,BE231,ASV4308,100.00,253,0,0,448,700,1,253,3.000000e-132,468
136,BE232,ASV283,100.00,253,0,0,449,701,1,253,3.000000e-132,468
137,BE233,ASV39,100.00,253,0,0,432,684,1,253,3.000000e-132,468
138,BE234,ASV452,95.65,253,11,0,443,695,1,253,6.000000e-114,407
139,BE235,ASV687,100.00,253,0,0,385,637,1,253,2.000000e-132,468
140,BE236,ASV4308,100.00,253,0,0,446,698,1,253,3.000000e-132,468
141,BE239,ASV90,100.00,253,0,0,383,635,1,253,2.000000e-132,468
142,BE240,ASV477,100.00,253,0,0,433,685,1,253,3.000000e-132,468
143,BE241,ASV171,100.00,253,0,0,437,689,1,253,3.000000e-132,468
144,BE242,ASV81,100.00,253,0,0,420,672,1,253,3.000000e-132,468
145,BE243,ASV1356,99.60,253,1,0,383,635,1,253,1.000000e-130,462
146,BE248,ASV266,100.00,253,0,0,414,666,1,253,3.000000e-132,468
147,BE249,ASV687,100.00,253,0,0,383,635,1,253,2.000000e-132,468
148,BE251,ASV1356,100.00,253,0,0,380,632,1,253,2.000000e-132,468
149,BE254,ASV1030,100.00,253,0,0,381,633,1,253,2.000000e-132,468
150,BE255,ASV1030,100.00,253,0,0,384,636,1,253,2.000000e-132,468
151,BE256,ASV2669,99.60,253,1,0,381,633,1,253,1.000000e-130,462
152,BE257,ASV90,100.00,253,0,0,380,632,1,253,1.000000e-132,468
153,BE258,ASV1356,99.60,253,1,0,379,631,1,253,1.000000e-130,462
154,BE259,ASV687,100.00,253,0,0,383,635,1,253,2.000000e-132,468
155,BE260,ASV1601,100.00,253,0,0,429,681,1,253,3.000000e-132,468
156,BE261,ASV19,100.00,253,0,0,412,664,1,253,3.000000e-132,468
157,BE264,ASV23,100.00,253,0,0,386,638,1,253,2.000000e-132,468
158,BE265,ASV360,100.00,253,0,0,433,685,1,253,3.000000e-132,468
159,BE268,ASV236,100.00,253,0,0,385,637,1,253,2.000000e-132,468
160,BE270,ASV150,100.00,253,0,0,383,635,1,253,1.000000e-132,468
161,BE275,ASV452,100.00,253,0,0,443,695,1,253,3.000000e-132,468
162,BE276,ASV452,100.00,253,0,0,441,693,1,253,3.000000e-132,468
163,BE277,ASV452,100.00,253,0,0,441,693,1,253,3.000000e-132,468

In [66]:
# function to get unique values 
def unique(list1): 
    x = np.array(list1) 
    return(np.unique(x))

In [70]:
IsolateMatches_list = df["sseqid"].tolist()
IsolateMatches_list = list(unique(IsolateMatches_list))
IsolateMatches_list

['ASV1030',
 'ASV1106',
 'ASV1114',
 'ASV12',
 'ASV13',
 'ASV1350',
 'ASV1356',
 'ASV1379',
 'ASV150',
 'ASV151',
 'ASV1592',
 'ASV1601',
 'ASV163',
 'ASV171',
 'ASV1811',
 'ASV188',
 'ASV19',
 'ASV1915',
 'ASV193',
 'ASV2066',
 'ASV2116',
 'ASV2203',
 'ASV2204',
 'ASV23',
 'ASV233',
 'ASV236',
 'ASV266',
 'ASV2669',
 'ASV270',
 'ASV2719',
 'ASV283',
 'ASV2888',
 'ASV296',
 'ASV302',
 'ASV321',
 'ASV3270',
 'ASV350',
 'ASV3528',
 'ASV3592',
 'ASV360',
 'ASV362',
 'ASV3772',
 'ASV3899',
 'ASV39',
 'ASV393',
 'ASV420',
 'ASV430',
 'ASV4308',
 'ASV452',
 'ASV4604',
 'ASV4621',
 'ASV477',
 'ASV481',
 'ASV4861',
 'ASV492',
 'ASV5115',
 'ASV522',
 'ASV5271',
 'ASV5417',
 'ASV5572',
 'ASV5578',
 'ASV58',
 'ASV600',
 'ASV6114',
 'ASV617',
 'ASV665',
 'ASV687',
 'ASV7471',
 'ASV765',
 'ASV77',
 'ASV792',
 'ASV8',
 'ASV81',
 'ASV891',
 'ASV90',
 'ASV91']

## Identify hyphal ASVs

* Too many RH ASVs to include
* Don't include for now, but use attributes to highlight any ASVs that make it into the tree otherwise

In [206]:
dfl2fc_CHCS = pandas.read_table('/home/be68/Hyphosphere/Exp10/DESeq2/dfl2fc-CHCS.txt', sep = "\t")
dfl2fc_CHBS = pandas.read_table('/home/be68/Hyphosphere/Exp10/DESeq2/dfl2fc-CHBS.txt', sep = "\t")
dfl2fc_RHCS = pandas.read_table('/home/be68/Hyphosphere/Exp10/DESeq2/dfl2fc-RHCS.txt', sep = "\t")
dfl2fc = dfl2fc_CHBS.append(dfl2fc_CHCS)
dfl2fc = dfl2fc.append(dfl2fc_RHCS)

sigtab = dfl2fc_CHBS.append(dfl2fc_CHCS)
sigtab.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ASV,Test,TimePoint
1,0.000000,NaN,NaN,NaN,NaN,NaN,ASV11489,CH-BS,1
2,0.162168,1.455070,3.093253,0.470401,0.638068,NaN,ASV11644,CH-BS,1
3,0.913138,-3.296519,3.034100,-1.086490,0.277262,NaN,ASV3656,CH-BS,1
4,15.109037,-0.425264,2.894952,-0.146898,0.883212,0.972331,ASV562,CH-BS,1
5,0.000000,NaN,NaN,NaN,NaN,NaN,ASV2718,CH-BS,1

In [207]:

sigtab = sigtab.loc[(sigtab.padj < 0.05) & (sigtab.log2FoldChange > 0)]

HA = sigtab.ASV.unique()
HA = list(HA)
#HA.sort()
len(HA)

200

## Identify top 100 ASVs for context

In [126]:
ASVabund = pandas.read_table('ASV_meanAbundances.txt', sep = "\t")
ASVabund.head()

,OTU,Phylum,Class,Family,Genus,BP,BS,CH,CS,RH,RT
1,ASV100,Proteobacteria,Alphaproteobacteria,Xanthobacteraceae,NaN,0.003115,0.004161,0.002490,0.003742,0.000230,0.000000
2,ASV1000,Verrucomicrobia,Verrucomicrobiae,Chthoniobacteraceae,Candidatus_Udaeobacter,0.000364,0.000745,0.000158,0.000268,0.000031,0.000000
3,ASV1002,Actinobacteria,Actinobacteria,Microbacteriaceae,Agromyces,0.000508,0.000406,0.000361,0.000407,0.000142,0.000000
4,ASV1003,Gemmatimonadetes,Gemmatimonadetes,Gemmatimonadaceae,NaN,0.000628,0.000274,0.000087,0.000534,0.000046,0.000000
5,ASV10035,Actinobacteria,Thermoleophilia,Solirubrobacteraceae,NaN,0.000000,0.000000,0.000000,0.000000,0.000036,0.000013

In [136]:
ASVabund['meanAbund'] = 0
ASVabund.head()
#np.mean(ASVabund["CS"], ASVabund["CH"]) #, ASVabund['RH'], ASVabund['CH'])

,OTU,Phylum,Class,Family,Genus,BP,BS,CH,CS,RH,RT,meanAbund
1,ASV100,Proteobacteria,Alphaproteobacteria,Xanthobacteraceae,NaN,0.003115,0.004161,0.002490,0.003742,0.000230,0.000000,0
2,ASV1000,Verrucomicrobia,Verrucomicrobiae,Chthoniobacteraceae,Candidatus_Udaeobacter,0.000364,0.000745,0.000158,0.000268,0.000031,0.000000,0
3,ASV1002,Actinobacteria,Actinobacteria,Microbacteriaceae,Agromyces,0.000508,0.000406,0.000361,0.000407,0.000142,0.000000,0
4,ASV1003,Gemmatimonadetes,Gemmatimonadetes,Gemmatimonadaceae,NaN,0.000628,0.000274,0.000087,0.000534,0.000046,0.000000,0
5,ASV10035,Actinobacteria,Thermoleophilia,Solirubrobacteraceae,NaN,0.000000,0.000000,0.000000,0.000000,0.000036,0.000013,0

In [145]:
dfA = ASVabund
dfA['sumAbund'] = dfA.BS + dfA.CS + dfA.CH + dfA.RH
dfA = dfA.sort_values(['sumAbund'], ascending = False)[:100]
TopASVs = list(dfA.OTU)
TopASVs
#df.sort(['A', 'B'], ascending=[1, 0])

['ASV11',
 'ASV17',
 'ASV20',
 'ASV21',
 'ASV8',
 'ASV19',
 'ASV18',
 'ASV6',
 'ASV28',
 'ASV22',
 'ASV16',
 'ASV13',
 'ASV15',
 'ASV12',
 'ASV38',
 'ASV41',
 'ASV48',
 'ASV42',
 'ASV37',
 'ASV45',
 'ASV43',
 'ASV99',
 'ASV51',
 'ASV56',
 'ASV54',
 'ASV26',
 'ASV59',
 'ASV60',
 'ASV61',
 'ASV68',
 'ASV78',
 'ASV35',
 'ASV72',
 'ASV80',
 'ASV73',
 'ASV79',
 'ASV46',
 'ASV89',
 'ASV83',
 'ASV57',
 'ASV91',
 'ASV23',
 'ASV110',
 'ASV100',
 'ASV104',
 'ASV113',
 'ASV107',
 'ASV161',
 'ASV96',
 'ASV74',
 'ASV97',
 'ASV114',
 'ASV117',
 'ASV71',
 'ASV112',
 'ASV39',
 'ASV122',
 'ASV123',
 'ASV86',
 'ASV101',
 'ASV109',
 'ASV140',
 'ASV47',
 'ASV82',
 'ASV50',
 'ASV111',
 'ASV141',
 'ASV227',
 'ASV139',
 'ASV169',
 'ASV178',
 'ASV76',
 'ASV234',
 'ASV129',
 'ASV142',
 'ASV125',
 'ASV77',
 'ASV115',
 'ASV85',
 'ASV134',
 'ASV174',
 'ASV189',
 'ASV66',
 'ASV144',
 'ASV366',
 'ASV152',
 'ASV224',
 'ASV167',
 'ASV173',
 'ASV162',
 'ASV136',
 'ASV180',
 'ASV190',
 'ASV44',
 'ASV216',
 'ASV219',
 'ASV217',
 'ASV143',
 'ASV128',
 'ASV263']

## Now join lists and prune tree
* Top ASVs = TopASVs
* Diff Abund asvs = HA
* Isolates and top blast hits = IsolateList + IsolateMatches_list

* master tree = t_rooted

In [156]:
IsolateList

['BE26',
 'BE27',
 'BE28',
 'BE29',
 'BE30',
 'BE31',
 'BE32',
 'BE33',
 'BE34',
 'BE35',
 'BE36',
 'BE38',
 'BE39',
 'BE40',
 'BE41',
 'BE42',
 'BE43',
 'BE44',
 'BE45',
 'BE46',
 'BE47',
 'BE48',
 'BE49',
 'BE50',
 'BE51',
 'BE52',
 'BE53',
 'BE54',
 'BE55',
 'BE56',
 'BE57',
 'BE59',
 'BE60',
 'BE61',
 'BE62',
 'BE63',
 'BE64',
 'BE65',
 'BE65B',
 'BE66',
 'BE68',
 'BE69',
 'BE70',
 'BE71',
 'BE72',
 'BE74',
 'BE75',
 'BE76',
 'BE79',
 'BE80',
 'BE81',
 'BE82',
 'BE83',
 'BE84',
 'BE85',
 'BE88',
 'BE91',
 'BE92',
 'BE93',
 'BE94',
 'BE95',
 'BE96',
 'BE97',
 'BE98',
 'BE100',
 'BE101',
 'BE102',
 'BE103',
 'BE104',
 'BE105',
 'BE107',
 'BE108',
 'BE109',
 'BE110',
 'BE112',
 'BE113',
 'BE114',
 'BE115',
 'BE116',
 'BE117',
 'BE118',
 'BE120',
 'BE121',
 'BE122',
 'BE123',
 'BE124',
 'BE125',
 'BE126',
 'BE127',
 'BE128',
 'BE153',
 'BE154',
 'BE156',
 'BE157',
 'BE159',
 'BE163',
 'BE164',
 'BE166',
 'BE167',
 'BE168',
 'BE170',
 'BE171',
 'BE172',
 'BE173',
 'BE177',
 'BE178',
 'BE179',
 'BE180',
 'BE181',
 'BE182',
 'BE183',
 'BE184',
 'BE186',
 'BE187',
 'BE190',
 'BE191',
 'BE193',
 'BE194',
 'BE195',
 'BE196',
 'BE197',
 'BE198',
 'BE201',
 'BE203',
 'BE206',
 'BE207',
 'BE212',
 'BE213',
 'BE215',
 'BE216',
 'BE219',
 'BE220',
 'BE222',
 'BE223',
 'BE224',
 'BE228',
 'BE231',
 'BE232',
 'BE233',
 'BE234',
 'BE235',
 'BE236',
 'BE239',
 'BE240',
 'BE241',
 'BE242',
 'BE243',
 'BE248',
 'BE249',
 'BE251',
 'BE254',
 'BE255',
 'BE256',
 'BE257',
 'BE258',
 'BE259',
 'BE260',
 'BE261',
 'BE264',
 'BE265',
 'BE268',
 'BE270',
 'BE275',
 'BE276',
 'BE277']

In [208]:
MasterList = TopASVs + HA + IsolateList + IsolateMatches_list
#len(MasterList)
MasterList = list(set(MasterList))
len(MasterList)

496

## Prune tree with master list

In [209]:
mt_rooted = t_rooted.getSubTree(MasterList)

In [210]:
mt_rooted.writeToFile(os.path.join(workDir, 'SeqofInt.tree'))

# Generate dataframes for iTOL

In [228]:
dfl2fc.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ASV,Test,TimePoint
1,0.000000,NaN,NaN,NaN,NaN,NaN,ASV11489,CH-BS,1
2,0.162168,1.455070,3.093253,0.470401,0.638068,NaN,ASV11644,CH-BS,1
3,0.913138,-3.296519,3.034100,-1.086490,0.277262,NaN,ASV3656,CH-BS,1
4,15.109037,-0.425264,2.894952,-0.146898,0.883212,0.972331,ASV562,CH-BS,1
5,0.000000,NaN,NaN,NaN,NaN,NaN,ASV2718,CH-BS,1

In [166]:
ASVabund.head()

,OTU,Phylum,Class,Family,Genus,BP,BS,CH,CS,RH,RT,meanAbund,sumAbund
1,ASV100,Proteobacteria,Alphaproteobacteria,Xanthobacteraceae,NaN,0.003115,0.004161,0.002490,0.003742,0.000230,0.000000,0.007276,0.010624
2,ASV1000,Verrucomicrobia,Verrucomicrobiae,Chthoniobacteraceae,Candidatus_Udaeobacter,0.000364,0.000745,0.000158,0.000268,0.000031,0.000000,0.001109,0.001203
3,ASV1002,Actinobacteria,Actinobacteria,Microbacteriaceae,Agromyces,0.000508,0.000406,0.000361,0.000407,0.000142,0.000000,0.000914,0.001317
4,ASV1003,Gemmatimonadetes,Gemmatimonadetes,Gemmatimonadaceae,NaN,0.000628,0.000274,0.000087,0.000534,0.000046,0.000000,0.000902,0.000940
5,ASV10035,Actinobacteria,Thermoleophilia,Solirubrobacteraceae,NaN,0.000000,0.000000,0.000000,0.000000,0.000036,0.000013,0.000000,0.000036

## Process dataframes
* Create a dataframe with names from MasterList
* Left join abundance dataframe to sequences in Master List
* generate dfl2fc indicators annd add attributes to dataframe

In [174]:
dfM = pandas.DataFrame(MasterList, columns = ["ASV"])
dfM = pandas.merge(dfM, ASVabund, left_on='ASV', right_on="OTU", how='left')
dfM.head()

,ASV,OTU,Phylum,Class,Family,Genus,BP,BS,CH,CS,RH,RT,meanAbund,sumAbund
0,ASV2719,ASV2719,Proteobacteria,Alphaproteobacteria,Rhizobiaceae,Aminobacter,0.000038,0.000155,0.000096,0.000025,0.000177,0.000013,0.000193,0.000453
1,BE42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASV2717,ASV2717,Armatimonadetes,Fimbriimonadia,Fimbriimonadaceae,NaN,0.000154,0.000030,0.000187,0.000040,0.000029,0.000011,0.000184,0.000286
3,BE41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BE47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [229]:
sigtab = dfl2fc.loc[(dfl2fc.padj < 0.05) & (dfl2fc.log2FoldChange > 0)]
sigtab = sigtab.groupby(['ASV', 'Test'], as_index=False).agg({"padj": "min"})
sigtab = sigtab.pivot(index = 'ASV', columns = "Test", values = "padj")




sigtab.head()

Test            CH-BS     CH-CS         RH-CS
ASV
ASV101   2.995563e-02  0.034742  8.431885e-11
ASV1018  1.699569e-05  0.000863           NaN
ASV1019  2.721585e-13       NaN           NaN
ASV102            NaN       NaN  2.708662e-03
ASV1022           NaN       NaN  1.102364e-03

In [232]:
#Note that this could be a good place to insert color codes into iTOL formated sheet
mask = sigtab['CH-BS'] < 0.05
column_name = 'CH-BS'
sigtab.loc[mask, column_name] = 1

mask = sigtab['CH-CS'] < 0.05
column_name = 'CH-CS'
sigtab.loc[mask, column_name] = 1

mask = sigtab['RH-CS'] < 0.05
column_name = 'RH-CS'
sigtab.loc[mask, column_name] = 1

sigtab.head()

Test     CH-BS  CH-CS  RH-CS
ASV
ASV101     1.0    1.0    1.0
ASV1018    1.0    1.0    NaN
ASV1019    1.0    NaN    NaN
ASV102     NaN    NaN    1.0
ASV1022    NaN    NaN    1.0

In [234]:
dfM = pandas.merge(dfM, sigtab, on = 'ASV', how='left')
dfM.head()

,ASV,OTU,Phylum,Class,Family,Genus,BP,BS,CH,CS,RH,RT,meanAbund,sumAbund,CH-BS,CH-CS,RH-CS
0,ASV2719,ASV2719,Proteobacteria,Alphaproteobacteria,Rhizobiaceae,Aminobacter,0.000038,0.000155,0.000096,0.000025,0.000177,0.000013,0.000193,0.000453,NaN,NaN,NaN
1,BE42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASV2717,ASV2717,Armatimonadetes,Fimbriimonadia,Fimbriimonadaceae,NaN,0.000154,0.000030,0.000187,0.000040,0.000029,0.000011,0.000184,0.000286,1.0,NaN,NaN
3,BE41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BE47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### overall attribute table

In [236]:
dfM.to_csv(os.path.join(workDir, 'SeqofInt_attributes.txt'), sep='\t', index=False)

In [ ]:
### Individual tables for iTOL templates

In [238]:
dfM['Taxonomy'] = dfM.Phylum + " " + dfM.Class + " " + dfM.Family

In [241]:
dfT = dfM[['ASV', 'Taxonomy']]

dfT.head()

       ASV                                          Taxonomy
0  ASV2719   Proteobacteria Alphaproteobacteria Rhizobiaceae
1     BE42                                               NaN
2  ASV2717  Armatimonadetes Fimbriimonadia Fimbriimonadaceae
3     BE41                                               NaN
4     BE47                                               NaN

In [243]:
dfT.to_csv(os.path.join(workDir, 'SeqofInt_leaflabels.txt'), sep='\t', index=False)